# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "headlamp"
displayName: "headlamp"
description: "headlamp is a web-based UI for Kubernetes cluster management."
version: 0.39.2
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: headlamp
    version: 0.39.2

deploymentProfiles:
  - name: "default"
    applicationProfiles:
      - application: "headlamp"
        profile: "default"

defaultNamespaces:
  headlamp: headlamp

namespaces:
  - name: headlamp
    labels:
      pod-security.kubernetes.io/enforce: privileged
      name: headlamp
