# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: kubevirt-helper
description: A Helm chart for KubeVirt Helper service
type: application
version: 1.6.0
appVersion: 1.6.0
annotations: {}
